Repository minio/docs, pull requests merged in 2022-05, with the labels that each got.

#474 Add Service account policies documentation
  source/security/minio-identity-management/policy-based-access-control.rst
Labels: tiny, community, external-contributor

#470 DOCS-439: MinIO Console refresh
  source/conf.py
  source/console/minio-console.rst
  source/images/minio-console-buckets.png
  source/images/minio-console-dashboard.png
  source/images/minio-console-login.png
  source/images/minio-console/console-bucket-create-bucket-with-locking.png
  source/images/minio-console/console-bucket-create-bucket.png
  source/images/minio-console/console-bucket-locking-compliance.png
  source/images/minio-console/console-bucket-locking.png
  source/images/minio-console/console-bucket-manage.png
  source/images/minio-console/console-bucket-overview.png
  source/images/minio-console/console-bucket.png
  source/images/minio-console/console-dashboard.png
  source/images/minio-console/console-diagnostics.png
  source/images/minio-console/console-drives.png
  source/images/minio-console/console-groups-assign.png
  source/images/minio-console/console-groups-create-group.png
  source/images/minio-console/console-groups.png
  source/images/minio-console/console-heal.png
  source/images/minio-console/console-health.png
  source/images/minio-console/console-iam-create.png
  source/images/minio-console/console-iam-details.png
  source/images/minio-console/console-iam.png
  source/images/minio-console/console-inspect.png
  source/images/minio-console/console-license.png
  source/images/minio-console/console-login.png
  source/images/minio-console/console-logs.png
  source/images/minio-console/console-metrics-simple.png
  source/images/minio-console/console-metrics.png
  source/images/minio-console/console-object-browser-locking.png
  source/images/minio-console/console-object-browser-object-details.png
  source/images/minio-console/console-object-browser.png
  source/images/minio-console/console-performance.png
  source/images/minio-console/console-profile.png
  source/images/minio-console/console-register.png
  source/images/minio-console/console-service-accounts-create.png
  source/images/minio-console/console-service-accounts.png
  source/images/minio-console/console-settings-configuration.png
  source/images/minio-console/console-settings-lambda.png
  source/images/minio-console/console-settings-notifications.png
  source/images/minio-console/console-settings-site-replication.png
  source/images/minio-console/console-settings-tiers.png
  source/images/minio-console/console-support-notifications.png
  source/images/minio-console/console-trace.png
  source/images/minio-console/console-users-create.png
  source/images/minio-console/console-users-details.png
  source/images/minio-console/console-users.png
  source/images/minio-console/console-watch.png
  source/images/minio-console/minio-console.png
  source/includes/common-installation.rst
  source/installation/deploy-minio-standalone.rst
  source/monitoring/metrics-alerts/collect-minio-metrics-using-prometheus.rst
  source/monitoring/metrics-alerts/minio-metrics-and-alerts.rst
  source/object-retention/bucket-versioning.rst
  source/object-retention/minio-object-locking.rst
  source/quickstart/container.rst
  source/quickstart/k8s.rst
  source/quickstart/linux.rst
  source/quickstart/macos.rst
  source/quickstart/windows.rst
Labels: Review

#482 Remove additional backticks from container quickstart
  source/quickstart/container.rst
Labels: RFM, tiny, community, external-contributor

#486 Match terms with MinIO Console
  source/console/minio-console.rst
Labels: priority: medium, RFM, tiny, community, external-contributor
