Repository minio/docs, pull requests merged in 2023-02, with the labels that each got.

#720 DOCS-690, DOCS-707: Release updates
  source/administration/console/managing-deployment.rst
  source/administration/console/managing-objects.rst
  source/includes/common/common-k8s-deprecation-audit-prometheus.rst
  source/operations/install-deploy-manage/deploy-minio-tenant.rst
  source/operations/monitoring/collect-minio-metrics-using-prometheus.rst
  source/reference/kubectl-minio-plugin/kubectl-minio-init.rst
  source/reference/kubectl-minio-plugin/kubectl-minio-tenant-create.rst
Labels: priority: medium, Review

#722 Port-Forwarding cleanups
  source/includes/common-installation.rst
  source/includes/common/common-install-operator-kubectl-plugin.rst
  source/includes/common/common-k8s-connect-operator-console.rst
  source/includes/k8s/common-minio-kes.rst
  source/includes/k8s/steps-deploy-tenant-cli.rst
  source/includes/openshift/deploy-minio-on-openshift.rst
  source/includes/openshift/steps-deploy-minio-tenant.rst
  source/operations/install-deploy-manage/deploy-minio-single-node-single-drive.rst
  source/operations/install-deploy-manage/deploy-minio-tenant.rst
  source/operations/install-deploy-manage/upgrade-minio-operator.rst
Labels: Review

#729 DOCS-728: Dropping Windows cruft
  source/includes/common/installation.rst
  source/includes/windows/quickstart.rst
  source/includes/windows/steps-deploy-minio-single-node-single-drive.rst
  source/index.rst
  source/operations/install-deploy-manage/deploy-minio-single-node-single-drive.rst
  source/url-excludes.yaml
Labels: Review

#734 User and group are no longer treated as flags
  source/reference/minio-mc-admin/mc-admin-policy.rst
Labels: WIP

#742 Improve SEO for Index + Quickstart Pages
  source/default-conf.py
  source/includes/k8s/quickstart.rst
  source/includes/linux/quickstart.rst
  source/includes/macos/quickstart.rst
  source/includes/windows/quickstart.rst
  source/index.rst
Labels: Review
