Repository minio/docs, pull requests merged in 2023-04, with the labels that each got.

#793 DOCS-779: Fix permission set for MinIO on KES
  source/includes/common/common-minio-kes-aws.rst
  source/includes/common/common-minio-kes-azure.rst
  source/includes/common/common-minio-kes-gcp.rst
  source/includes/common/common-minio-kes-hashicorp.rst
  source/includes/linux/steps-configure-minio-kes-aws.rst
  source/includes/linux/steps-configure-minio-kes-azure.rst
  source/includes/linux/steps-configure-minio-kes-gcp.rst
  source/includes/linux/steps-configure-minio-kes-hashicorp.rst
  source/operations/server-side-encryption/configure-minio-kes-aws.rst
  source/operations/server-side-encryption/configure-minio-kes-azure.rst
  source/operations/server-side-encryption/configure-minio-kes-gcp.rst
  source/operations/server-side-encryption/configure-minio-kes-hashicorp.rst
Labels: priority: medium, Review

#797 General work on releases
  source/administration/identity-access-management/ad-ldap-access-management.rst
  source/administration/minio-console.rst
  source/operations/external-iam/configure-ad-ldap-external-identity-management.rst
  source/reference/minio-mc-admin.rst
  source/reference/minio-mc-admin/mc-admin-config.rst
  source/reference/minio-mc-admin/mc-admin-idp-ldap.rst
  source/reference/minio-mc-admin/mc-admin-user-sts.rst
Labels: Review

#803 Adding more EDU videos
  source/administration/object-management.rst
  source/administration/object-management/object-lifecycle-management.rst
  source/administration/object-management/object-retention.rst
  source/administration/object-management/object-versioning.rst
  source/includes/container/installation.rst
  source/includes/container/quickstart.rst
  source/includes/k8s/quickstart.rst
  source/includes/linux/quickstart.rst
  source/includes/macos/quickstart.rst
  source/includes/windows/quickstart.rst
  source/index.rst
  source/operations/monitoring.rst
  source/operations/monitoring/collect-minio-metrics-using-prometheus.rst
Labels: priority: medium, Review

#816 DOCS-784: Fix Kafka TLS Client Auth reference
  source/includes/common-mc-admin-config.rst
Labels: Review

#817 Specify usage of `mc` in gateway migration
  source/operations/install-deploy-manage/migrate-fs-gateway.rst
Labels: doc-change-request

#825 Patching replication docs for version match requirement
  source/administration/bucket-replication.rst
  source/includes/common-replication.rst
  source/operations/data-recovery/recover-after-site-failure.rst
  source/operations/install-deploy-manage/multi-site-replication.rst
Labels: Review
