Repository minio/docs, pull requests merged in 2023-08, with the labels that each got.

#929 DOCS-911: Improving erasure coding core concepts
  source/glossary.rst
  source/images/architecture/architecture-erasure-set-shard.svg
  source/images/architecture/architecture-load-balancer-multi-pool.svg
  source/images/architecture/erasure-coding-shard-write-quorum-split-brain.svg
  source/images/availability/availability-erasure-sharding-degraded-set.svg
  source/images/availability/availability-erasure-sharding-striped.svg
  source/images/erasure/erasure-coding-erasure-set-shard-distribution.svg
  source/images/erasure/erasure-coding-erasure-set.svg
  source/images/erasure/erasure-coding-possible-parity.svg
  source/images/erasure/erasure-coding-shard-healing.svg
  source/images/erasure/erasure-coding-shard-read-quorum.svg
  source/images/erasure/erasure-coding-shard-reconstruction.svg
  source/images/erasure/erasure-coding-shard-split-brain.svg
  source/images/erasure/erasure-coding-shard-write-quorum.svg
  source/images/erasure/erasure-coding-shard.svg
  source/operations/concepts/architecture.rst
  source/operations/concepts/availability-and-resiliency.rst
  source/operations/concepts/erasure-coding.rst
  source/reference/minio-server/minio-server.rst
Labels: WIP

#935 DOCS-872: Update condition key list
  source/administration/identity-access-management/policy-based-access-control.rst
  source/operations/concepts/erasure-coding.rst
  source/reference/minio-server/minio-server.rst
Labels: Review

#946 Adding C++ SDK into the list
  source/developers/minio-drivers.rst
Labels: doc-change-request

#961 DOCS-957: Fixed location for console location
  source/integrations/setup-nginx-proxy-with-minio.rst
Labels: community

#960 DOCS-898: Synchronous Bucket Notifications, config API secret redaction
  source/administration/monitoring/bucket-notifications.rst
  source/developers/transforms-with-object-lambda.rst
  source/includes/common-mc-admin-config.rst
  source/includes/common-minio-external-auth.rst
  source/reference/minio-mc-admin/mc-admin-config.rst
  source/reference/minio-server/minio-server.rst
Labels: priority: medium, Review
