Repository minio/docs, pull requests merged in 2023-09, with the labels that each got.

#985 DOCS-934: Clean up container procedures
  source/includes/container/installation.rst
  source/includes/container/steps-upgrade-minio-deployment.rst
  source/includes/linux/steps-upgrade-minio-deployment.rst
  source/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.rst
  source/operations/install-deploy-manage/upgrade-minio-deployment.rst
  source/operations/manage-existing-deployments.rst
  source/operations/network-encryption.rst
  source/url-excludes.yaml
Labels: priority: medium, Review

#1003 DOCS-987: Fixing prometheus metrics to pull from Minio Server docs list
  .gitignore
  Makefile
  source/operations/monitoring/metrics-and-alerts.rst
  sync-minio-server-docs.sh
Labels: Review

#992 Warn user to use XFS in EBS Volumes
  source/operations/install-deploy-manage/deploy-minio-tenant.rst
Labels: doc-change-request
