Repository minio/docs, pull requests merged in 2024-05, with the labels that each got.

#1206 FIXUP: Existing object replication is on by default
  source/administration/bucket-replication.rst
  source/reference/minio-server/settings/kes.rst
Labels: Review, tiny

#1211 DOCS-1159: RELEASE.2024-03-15T01-07-19Z
  source/operations/concepts/thresholds.rst
  source/reference/minio-server/settings/core.rst
  source/reference/minio-server/settings/storage-class.rst
Labels: Review

#1215 DOCS-1190: RELEASE.2024-04-18T19-09-19Z
  source/administration/object-management/object-versioning.rst
  source/default-conf.py
  source/includes/linux/common-installation.rst
  source/includes/linux/steps-upgrade-minio-deployment.rst
  source/operations/install-deploy-manage/upgrade-minio-deployment.rst
  source/operations/install-deploy-manage/upgrade-minio-tenant.rst
  source/url-excludes.yaml
Labels: Review

#1232 Fixed typo in container documentation
  source/includes/container/quickstart.rst
Labels: community, external-contributor
